id: aimania_add_api_to_backend
learningObjectives:
  - Using the GPT-3 API to generate a product description
hints:
  - Check if the user entered a description. If not, use the GPT-3 API to generate a description.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "Now, we have to integrate the API into our backend."
            delay: 700
          - text: "Check for empty descriptions in the backend and use the GPT-3 API to generate a description if the user didn't enter one."
            delay: 800
          - text: "See the [Open AI docs](https://beta.openai.com/docs/api-reference/completions/create) for more information on how to use the API. Enter a suitable prompt to generate description from the title."
            delay: 1000
          - text: "Remember: You have to use the openai package to use the API."
            delay: 1300
          - text: "Create a PR when you're done and I'll review it."
            delay: 1600
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: head-of-rd
                message: "On it! I'll review the changes as soon as possible!"
            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: "On it! I'll review the changes as soon as possible!"
                    delay: 1500
        github_pr_workflow_complete_success:
          if:
            conditions:
              - conditionId: github_does_file_contain
                equals: true
                params:
                  fileName: "backend/package.json"
                  regex: openai
            then:
              do:
                - actionId: bot_message
                  params:
                    person: head-of-rd
                    messages:
                      - text: Looking good! You can merge the PR now.
                        delay: 1500
                - actionId: github_pr_approve
                  params:
                    person: head-of-rd
                    message: Looking good! You can merge the PR now.
            else:
              do:
                - actionId: bot_message
                  params:
                    person: head-of-rd
                    messages:
                      - text: "You haven't integrated the API into the backend yet. Please do so and create a new PR."
                        delay: 1000
                      - text: "Remember: You have to use the openai package to use the API."
                        delay: 1500
                - actionId: github_pr_reject
                  params:
                    person: head-of-rd
                    message: "You haven't integrated the API into the backend yet. Please do so and create a new PR."
        github_pr_workflow_complete_failure:
          do:
            - actionId: github_pr_reject
              params:
                person: head-of-rd
                message: Some PR checks are failing. Please look into it and create a new PR.

            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: Some PR checks are failing. Please look into it and create a new PR.
                    delay: 2500
        github_pr_merged:
          do:
            - actionId: finish_step

githubActions:
  backend:
    capabilities:
      - axios
      - dotenv
    testFile: "test.js"
